config/routes.rb
Rails.application.routes.draw do
  resources :items
  root 'site#index'
  get '/about' => 'site#about'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_product, only: [:show, :edit, :update, :destroy]

    def index
      @items = Item.all
      @choice = [" ", 'A - Z', "Z - A", "Highest - Lowest Price", "Lowest - Highest Price"]
    #  if params[:order]
    #  Item.order("#{params[:order]} ASC").all
    ap = params[:order]
    ap = URI.unescape(ap.to_s)
      if ap == "Highest - Lowest Price"
        id = Item.order("price DESC")
        #highest price to lowest
      elsif ap == 'Lowest - Highest Price'
        id =  Item.order("price ASC")
        # sorts from a - z
      elsif ap == 'A - Z'
        id = Item.order("name ASC")
        #sorts from z - a
      elsif ap == "Z - A"
        id = Item.order("name DESC")
      else
        id = Item.order("name ASC")
      end
      @items = id
    end


  def create
   @item = Item.new(item_params)
   if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
   end


  def new
    @item = Item.new
  end

  def show

  end

  def edit

  end

  def update
    if @item.update_attributes(item_params)
       redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path

  end

    private
    def find_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name)
    end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
    @items = Item.all 
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper



  # def sorter(choice = [])
  #   choice.each do |e|
  #     #lowest price to highest
  #     if params[:object] == 'Highest - Lowest Price'
  #         SELECT * FROM Items
  #         ORDER BY price DESC;
  #       #highest price to lowest
  #     elsif params[:object] == 'Lowest - Highest Price'
  #         SELECT * FROM Items
  #         ORDER BY price ASC;
  #       # sorts from a - z
  #     elsif params[:object] == 'A - Z'
  #         SELECT * FROM Items
  #         ORDER BY name ASC;
  #       #sorts from z - a
  #     elsif params[:object] == "Z - A"
  #         SELECT * FROM Items
  #         ORDER BY name DESC;
  #
  #         Items.order()
  #     else
  #
  #     end
  #   end
  # end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/items/edit.html.erb
<h1>Edit <%= @item.name %></h1>

<%= form_for(@item) do |f| %>
  <%= f.label(:name) %>
  <%= f.text_field(:name) %>
  <%= f.submit('Update') %>
<% end %>

app/views/items/index.html.erb
<h1>Track List</h1>





    <label>Sort by: </label>
    <select name="stuff" onchange="resort(this)">
      <% @choice.each do |c|%>
          <option value="<%= c %>"><%= c %></option>
      <% end %>
    </select>



<ul onload="fnDraw()">
<% @items.each do |item| %>
  <li>
    <%= item.name %>
    <%= item.price %>
    <%= link_to('Destroy', item_path(item.id), method: :delete, 'data-confirm' => 'Are you sure?') %>
  </li>
  <% end %>
</ul>


<%= link_to('Add a new track!', new_item_path, class: "link") %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= form_for(@item) do |f| %>
  <div>
    <%= f.label(:name) %>
    <%= f.text_field(:name) %>
  </div>
  <div>
    <%= f.submit('save') %>
  </div>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<div>
  <%= @item.description %>
</div>

<%= link_to('&laquo; Back to all tracks'.html_safe, items_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Audiowide|Nunito' rel='stylesheet' type='text/css'>
  <title>Digital|Grooves</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <%= link_to('Home', root_path, class: "links") %>
    <span>&nbsp;|&nbsp;</span>
    <%= link_to('About', about_path, class: "links") %>
    <span>&nbsp;|&nbsp;</span>
    <%= link_to('Tracks', items_path, class: "links") %>
  </nav>
  <div id="wrapper">
    <header>

    </header>
    <section id="main-content">
<%= yield %>
    </section>
    <footer>
      copyright &copy; <%= Time.now.year %>
    </footer>
  </div>
</body>
</html>

app/views/site/about.html.erb
<h1>Know me.</h1>

<p>Hodor hodor HODOR! Hodor hodor - hodor; hodor hodor. Hodor hodor - hodor;
  hodor hodor hodor! Hodor! Hodor hodor, hodor hodor hodor hodor! Hodor!
  Hodor hodor, hodor, hodor. Hodor hodor hodor hodor?! Hodor hodor - hodor;
  hodor hodor?! Hodor, hodor. Hodor. Hodor, hodor - hodor, hodor. Hodor hodor?
  Hodor, hodor. Hodor. Hodor, hodor hodor HODOR hodor, hodor HODOR hodor, hodor
  hodor?!</p>

app/views/site/index.html.erb
<h1>Digital Grooves</h1>

<p>The stylish way to create your very own non-functional playlist.</p>